### ISSUE TITLE
box.ludobox.net certificate expired

### ISSUE THREAD

**Issue by arthurlutz** [ludobox/ludobox-ui#115]
![Screenshot from 2020-01-22 11-46-11](https://user-images.githubusercontent.com/108437/72887892-d3c49880-3d0c-11ea-8a34-0c88123e2af8.png)

**Comment by arthurlutz** [comment]
If you accept it, you end up on a "502 Bad Gateway - nginx/1.6.2"

**Comment by clemsos** [comment]
Whoops…. should be back up again

**Comment by arthurlutz** [comment]
Hey ! Thanks for fixing that back in january! It's that time again, the certificate expired. 

I was going to look for creative-commons card games we could integrate in https://github.com/Pro1d/CovidCardGame/ to play during lockdown...

**Comment by clemsos** [comment]
ok that should be back up now !
